name: Linux Build

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build for Linux
        shell: pwsh
        run: |
          python -m pip install -r requirements.txt
          pyinstaller --onefile ./main.py
          mv ./dist/main ./dist/pre_linux_amd64
          ls -alhR

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          # release_name: ${{ steps.version.outputs.version }}
          release_name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          # tag_name: ${{ github.ref }}
          # body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/pre_linux_amd64
          asset_name: Linux (amd64)
          asset_content_type: application/sh

permissions:
  contents: write